get rid of vectorized ops which were causing compatibility issues
the vectorized ops in `AccuracyBenchmark.filter_rows()` were causing problems. First there were
julia 0.5-0.6 compatibility issues. I think we added some dots for some of them, and some were
supposedly handled by the Compat package. Then I got this error after doing `Pkg.update()` today:

```
ERROR: LoadError: BoundsError: attempt to access ()
  at index [1]
Stacktrace:
 [1] macro expansion at /home/steve/.julia/v0.6/DataArrays/src/dataarray.jl:254 [inlined]
 [2] macro expansion at /home/steve/.julia/v0.6/Compat/src/ngenerate.jl:0 [inlined]
 [3] isna(::DataArrays.DataArray{Bool,1}) at /home/steve/.julia/v0.6/Compat/src/ngenerate.jl:57
 [4] filter_rows(::DataFrames.DataFrame, ::DataFrames.DataFrame, ::Symbol) at /home/steve/.julia/v0.6/Celeste/src/AccuracyBenchmark.jl:623
 [5] get_scores_df(::DataFrames.DataFrame, ::DataFrames.DataFrame, ::Nullable{DataFrames.DataFrame}) at /home/steve/.julia/v0.6/Celeste/src/AccuracyBenchmark.jl:664
 [6] score_predictions(::DataFrames.DataFrame, ::Array{DataFrames.DataFrame,1}) at /home/steve/.julia/v0.6/Celeste/src/AccuracyBenchmark.jl:718
 [7] include_from_node1(::String) at ./loading.jl:539
 [8] include(::String) at ./sysimg.jl:14
 [9] process_options(::Base.JLOptions) at ./client.jl:305
 [10] _start() at ./client.jl:371
while loading /home/steve/work/Celeste.jl/benchmark/accuracy/score_predictions.jl, in expression starting on line 14
```

Not even going to try to debug that one. Instead let's just use simple iterative code which is
basically just as concise and I don't think sacrifices any speed in Julia. (Maybe is even faster?
Doesn't matter in this context anyway.)

For the record, here's a complete log of what things look like right now, which I verified matches
the output from just after my previous commit:

```
15:49 steve@fisher:~/work/Celeste.jl/benchmark/accuracy$ julia write_ground_truth_catalog_csv.jl coadd            [0]
Writing '/home/steve/work/Celeste.jl/benchmark/accuracy/output/stripe82_coadd_catalog.csv'...
Renaming /home/steve/work/Celeste.jl/benchmark/accuracy/output/stripe82_coadd_catalog.csv -> /home/steve/work/Celeste.jl/benchmark/accuracy/output/stripe82_coadd_catalog_69f2cbf0f6.csv

15:49 steve@fisher:~/work/Celeste.jl/benchmark/accuracy$ julia sdss_rcf_to_csv.jl \                               [0]
>     --objid-csv output/stripe82_coadd_catalog_69f2cbf0f6.csv
Reading Celeste.SDSSIO.RunCamcolField(4263, 5, 119)...
Loading primary catalog from /home/steve/.julia/v0.6/Celeste/test/data/4263/5/119/photoObj-004263-5-0119.fits
Loaded 1081 objects from catalog
Reading 'output/stripe82_coadd_catalog_69f2cbf0f6.csv'...
Matched 1081 objects to objid catalog
Writing '/home/steve/work/Celeste.jl/benchmark/accuracy/output/sdss_4263_5_119_primary.csv'...
Renaming /home/steve/work/Celeste.jl/benchmark/accuracy/output/sdss_4263_5_119_primary.csv -> /home/steve/work/Celeste.jl/benchmark/accuracy/output/sdss_4263_5_119_primary_8cd0750893.csv

15:50 steve@fisher:~/work/Celeste.jl/benchmark/accuracy$ julia run_celeste_on_field.jl --use-full-initialization \
>     output/sdss_4263_5_119_primary_8cd0750893.csv
Reading 'output/sdss_4263_5_119_primary_8cd0750893.csv'...
Loaded 549 sources...
[1]<1> processed objid 8647474692482138369 in 28.340303894 secs
...
[1]<1> processed objid 8647474692482203842 in 1.389187125 secs
Writing '/home/steve/work/Celeste.jl/benchmark/accuracy/output/sdss_4263_5_119_predictions.csv'...
Renaming /home/steve/work/Celeste.jl/benchmark/accuracy/output/sdss_4263_5_119_predictions.csv -> /home/steve/work/Celeste.jl/benchmark/accuracy/output/sdss_4263_5_119_predictions_d651f953c5.csv

16:19 steve@fisher:~/work/Celeste.jl/benchmark/accuracy$ julia score_predictions.jl output/stripe82_coadd_catalog_69f2cbf0f6.csv output/sdss_4263_5_119_primary_8cd0750893.csv output/sdss_4263_5_119_predictions_d651f953c5.csv
Reading 'output/stripe82_coadd_catalog_69f2cbf0f6.csv'...
Reading 'output/sdss_4263_5_119_primary_8cd0750893.csv'...
Reading 'output/sdss_4263_5_119_predictions_d651f953c5.csv'...
549 objids in common
13×6 DataFrames.DataFrame
│ Row │ N   │ first     │ second    │ diff       │ diff_sd    │ field                         │
├─────┼─────┼───────────┼───────────┼────────────┼────────────┼───────────────────────────────┤
│ 1   │ 547 │ 0.023766  │ 0.0786106 │ -0.0548446 │ 0.010881   │ missed_stars                  │
│ 2   │ 547 │ 0.0493601 │ 0.0274223 │ 0.0219378  │ 0.00840828 │ missed_galaxies               │
│ 3   │ 547 │ 0.332059  │ 0.289855  │ 0.0422039  │ 0.0088442  │ position                      │
│ 4   │ 547 │ 0.253688  │ 0.237734  │ 0.0159537  │ 0.0145987  │ reference_band_flux_mag       │
│ 5   │ 547 │ 1.74914   │ 1.96552   │ -0.216379  │ 0.34267    │ reference_band_flux_nmgy      │
│ 6   │ 132 │ 19.4795   │ 15.1686   │ 4.31095    │ 1.37118    │ angle_deg                     │
│ 7   │ 255 │ 0.311123  │ 0.193113  │ 0.11801    │ 0.0207951  │ de_vaucouleurs_mixture_weight │
│ 8   │ 255 │ 0.218483  │ 0.160667  │ 0.057816   │ 0.00986771 │ minor_major_axis_ratio        │
│ 9   │ 255 │ 2.01317   │ 0.663602  │ 1.34956    │ 0.638934   │ half_light_radius_px          │
│ 10  │ 487 │ 1.25981   │ 0.723021  │ 0.536791   │ 0.0470827  │ color_log_ratio_ug            │
│ 11  │ 543 │ 0.377395  │ 0.203802  │ 0.173593   │ 0.01939    │ color_log_ratio_gr            │
│ 12  │ 547 │ 0.266521  │ 0.162183  │ 0.104339   │ 0.0145795  │ color_log_ratio_ri            │
│ 13  │ 545 │ 0.404     │ 0.179009  │ 0.224991   │ 0.0199832  │ color_log_ratio_iz            │
```